### ISSUE TITLE
Change wercker.yml

### ISSUE THREAD

**Issue by joshcummingsdesign** [joshcummingsdesign/grizzly-wp#146]
to the following (example includes Pattern Lab):

```
box: ubuntu:14.04
build:
  steps:
    - install-packages:
        packages: git curl phpunit
    - script:
        name: install dependencies
        code: |-
          pear install PHP_CodeSniffer
          curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
          apt-get -y install nodejs
          npm install -g bower
          npm install -g gulp
    - npm-install
    - script:
        name: compile assets
        code: |-
          bower install --allow-root
          gulp --production
    - script:
        name: coding standards
        code: phpcs --standard=phpcs.xml
    - script:
        name: php unit tests
        code: phpunit
    - script:
        name: js unit tests
        code: npm test
    - script:
        name: cleanup
        code: |-
          rm -rf .git .editorconfig .gitignore .jshintignore .jshintrc
          mv wp-content ../wp-content
          mkdir ../patternlab && mv patternlab/public/* ../patternlab/
          mkdir ../trash && mv * ../trash/ && rm -rf ../trash
          mv ../wp-content ./ && mv ../patternlab ./
  after-steps:
    - slack-notifier:
        url: $SLACK_URL
        username: wercker
        notify_on: failed
deploy-staging:
  steps:
  - install-packages:
    packages: rsync openssh-client
  - add-to-known_hosts:
      hostname: $STG_HOST
      fingerprint: $FINGERPRINT
  - add-ssh-key:
      keyname: DEPLOY_KEY
  - script:
      name: deploy code
      code: |-
        rsync -qrz --partial --delete --exclude uploads --exclude plugins wp-content/ $STG_USER@$STG_HOST:applications/$STG_DB/public_html/wp-content/
        rsync -qrz --partial --delete wp-content/plugins/grizzly-builder $STG_USER@$STG_HOST:applications/$STG_DB/public_html/wp-content/plugins/
        rsync -qrz --partial --delete patternlab/ $STG_USER@$STG_HOST:applications/$STG_DB/public_html/patternlab/
  after-steps:
    - slack-notifier:
        url: $SLACK_URL
        username: wercker
        notify_on: failed
deploy-prod:
  steps:
  - install-packages:
    packages: rsync openssh-client
  - add-to-known_hosts:
      hostname: $PROD_HOST
      fingerprint: $FINGERPRINT
  - add-to-known_hosts:
      hostname: $STG_HOST
      fingerprint: $FINGERPRINT
  - add-ssh-key:
      keyname: DEPLOY_KEY
  - script:
      name: deploy code
      code: |-
        rsync -qrz --partial --delete --exclude uploads --exclude plugins wp-content/ $PROD_USER@$PROD_HOST:applications/$PROD_DB/public_html/wp-content/
  - script:
      name: deploy database
      code: |-
        ssh $STG_USER@$STG_HOST "cd applications/$STG_DB/public_html; wp db export prod.sql;"
        rsync -qrz --partial $STG_USER@$STG_HOST:applications/$STG_DB/public_html/prod.sql ./
        ssh $STG_USER@$STG_HOST "rm applications/$STG_DB/public_html/prod.sql"
        rsync -qrz --partial prod.sql $PROD_USER@$PROD_HOST:applications/$PROD_DB/public_html/prod.sql && rm prod.sql
        ssh $PROD_USER@$PROD_HOST "cd applications/$PROD_DB/public_html; wp db reset --yes; wp db import prod.sql; wp search-replace $STG_HOST $PROD_HOST; rm prod.sql"
  - script:
      name: deploy plugins
      code: |-
        rsync -qrz --partial --delete $STG_USER@$STG_HOST:applications/$STG_DB/public_html/wp-content/plugins/ wp-content/plugins/
        rsync -qrz --partial --delete --exclude w3-total-cache wp-content/plugins/ $PROD_USER@$PROD_HOST:applications/$PROD_DB/public_html/wp-content/plugins/
        mv wp-content/plugins/grizzly-builder ../grizzly-builder
        rm -rf wp-content/plugins/*
        mv ../grizzly-builder ./
  - script:
      name: deploy uploads
      code: |-
        rsync -qrz --partial --delete $STG_USER@$STG_HOST:applications/$STG_DB/public_html/wp-content/uploads/ wp-content/uploads/
        rsync -qrz --partial --delete wp-content/uploads/ $PROD_USER@$PROD_HOST:applications/$PROD_DB/public_html/wp-content/uploads/
        rm -rf wp-content/uploads
  after-steps:
    - slack-notifier:
        url: $SLACK_URL
        username: wercker
        notify_on: failed
```
