### ISSUE TITLE
Owl Carousel 2 Flashing Bug

### ISSUE THREAD

**Issue by joshcummingsdesign** [joshcummingsdesign/grizzly-wp#24]
Add the following to _sliders.scss:

```css
// Fixes flashing bug
.owl-item {
	backface-visibility: hidden;
	transform: translateZ(0) scale(1.0, 1.0);
}
```
